@startuml

'JAVA
'//////////////////////////////////////////////
package app{
class App{
}
}


package java{

package coffeeTypes{

package americano{
class Americano{
- Color: color
- int: volume
- Map<String, Integer>: ingredients
+ Color: getColor()
+ int: getVolume()
+ Map<String, Integer>: getIngredients()
}
class AmericanoFactory{
+ Coffee: createCoffee(String type)
}

}

package caffeLatte{
class CaffeLatte{
- Color: color
- int: volume
- Map: ingredients
+ Color: getColor()
+ int: getVolume()
+ Map: getIngredients()
}
class CaffeLatteFactory{
+ Coffee: createCoffee(String type)
}
}

package cappoucciono{
class Cappoucciono{
- Color: color
- int: volume
- Map: ingredients
+ Color: getColor()
+ int: getVolume()
+ Map: getIngredients()
}
class CappouccionoFactory{
+ Coffee: createCoffee(String type)
}
}

package cortado{
class Cortado{
- Color: color
- int: volume
- Map: ingredients
+ Color: getColor()
+ int: getVolume()
+ Map: getIngredients()
}

class CortadoFactory{
+ Coffee: createCoffee(String type)
}
}

package expresso{
class Expresso{
- Color: color
- int: volume
- Map: ingredients
+ Color: getColor()
+ int: getVolume()
+ Map: getIngredients()
}

class ExpressoFactory{
+ Coffee: createCoffee(String type)
}
}

package flatWhite{
class FlateWhite{
- Color: color
- int: volume
- Map: ingredients
+ Color: getColor()
+ int: getVolume()
+ Map: getIngredients()
}
class FlateWhiteFactory{
+ Coffee: createCoffee(String type)
}
}

package latteMacchiato{
class LatteMacchiato{
- Color: color
- int: volume
- Map: ingredients
+ Color: getColor()
+ int: getVolume()
+ Map: getIngredients()
}
class LatteMacchiatoFactory{
+ Coffee: createCoffee(String type)
}
}

package lungo{
class Lungo{
- Color: color
- int: volume
- Map: ingredients
+ Color: getColor()
+ int: getVolume()
+ Map: getIngredients()
}

class LungoFactory{
+ Coffee: createCoffee(String type)
}
}

package macchiato{
class Macchiato{
- Color: color
- int: volume
- Map: ingredients
+ Color: getColor()
+ int: getVolume()
+ Map: getIngredients()
 }
class MacchiatoFactory{
+ Coffee: createCoffee(String type)
}
}

package mocha{
class Mocha{
- Color: color
- int: volume
- Map: ingredients
+ Color: getColor()
+ int: getVolume()
+ Map: getIngredients()
}

class MochaFactory{
+ Coffee: createCoffee(String type)
}
}
}

CoffeeFactory <|.up. AmericanoFactory
CoffeeFactory <|.up. CaffeLatteFactory
CoffeeFactory <|.up. CappouccionoFactory
CoffeeFactory <|.up. CortadoFactory
CoffeeFactory <|.up. ExpressoFactory
CoffeeFactory <|.up. FlateWhiteFactory
CoffeeFactory <|.up. LatteMacchiatoFactory
CoffeeFactory <|.up. LungoFactory
CoffeeFactory <|.up. MacchiatoFactory
CoffeeFactory <|.up. MochaFactory


'//////////////////////////////////////////////

package ingredients{
abstract class Ingredients{
protected Coffee coffee;
+ Calculator: calculator
+ Color: getColor()
+ int: getVolume()
+ Map: getIngredients()
}

class Milk {
+ Color: getColor()
+ int: getVolume()
+ Map: getIngredients()
}
class Water {
+ Color: getColor()
+ int: getVolume()
+ Map: getIngredients()
}

package beansType{
class BeanNestle {
+ Color: getColor()
+ int: getVolume()
+ Map: getIngredients()
}

class BeanMerild {
+ Color: getColor()
+ int: getVolume()
+ Map: getIngredients()
}

class BeanDavidoff {
+ Color: getColor()
+ int: getVolume()
+ Map: getIngredients()
}
}

}
Ingredients <|-- Milk
Ingredients <|-- Water
Ingredients <|-- BeanNestle
Ingredients <|-- BeanMerild
Ingredients <|-- BeanDavidoff

'//////////////////////////////////////////////

package entities{
class Users{
- String: firstname
- String: lastname
- String: email
- String: password
}


interface Coffee{
+ Color: getColor()
+ int: getVolume()
+ Map: getIngredients()
}
}

'//////////////

 Coffee <|.up.. Ingredients
 Coffee <|... Americano
 Coffee <|... CaffeLatte
 Coffee <|... Cappoucciono
 Coffee <|... Cortado
 Coffee <|... Expresso
 Coffee <|... FlateWhite
 Coffee <|... LatteMacchiato
 Coffee <|... Lungo
 Coffee <|... Macchiato
 Coffee <|... Mocha

 Coffee <... AmericanoFactory
 Coffee <... CaffeLatteFactory
 Coffee <... CappouccionoFactory
 Coffee <... CortadoFactory
 Coffee <... ExpressoFactory
 Coffee <... FlateWhiteFactory
 Coffee <... LatteMacchiatoFactory
 Coffee <... LungoFactory
 Coffee <... MacchiatoFactory
 Coffee <... MochaFactory

interface CoffeeFactory{
+ Coffee: createCoffee(String type)
}

class Calculator{
+ Map<String,Integer>: coffeeIngredients
+ Color: calculateNewColor(Corlor color, int amount)
+ double: calculateNewVolume(double cm3)
+ Map<String,Integer>: calculateNewIngredients(Ingredients ingredient)
}

Calculator <--right-- Ingredients
package pesistences{
class UserMapper{
+ Users: login()
+ boolean: creatUser()
}

class CoffeeMapper{
+ List<Coffee>: favorites
+ boolean: addToFavorites(user_id, CoffeeName)
+ List<Coffee>: getFavorites(user_id)
}

CoffeeMapper -up-> Users
UserMapper -up-> Users

class ConnectionPool{
- ConnectionPool: instance
- HikariDatasource:
- Logger: LOGGER
- ConnectionPool: getInstance()
+ Connection: getConnection
+ void: close()
- HikariDataSource: createHikariConnectionPool()
}

App ----> ConnectionPool
}

'EXCEPTIONS
'/////////////////////////////////////
package exceptions{
class DatabaseExceptions
class exceptions
}
ConnectionPool --> DatabaseExceptions

'CONTROLLERS
'/////////////////////////////////////
package controllers{
class UserController{
+ void: addRoutes()
+ void: creatUser()
+ void: login()
+ void: logout()
}

class CoffeeController{
+ void: createCoffee()
+ void: addToFavorites()
+ void: getFavorites()
}
}

CoffeeController --up--> App
CoffeeController --up--> CoffeeMapper
CoffeeController ----> Users

CoffeeController --> Coffee
CoffeeController --> CoffeeFactory
CoffeeController --left--> Milk
CoffeeController --left--> Water
CoffeeController --left--> BeanDavidoff
CoffeeController --left--> BeanMerild
CoffeeController --left--> BeanNestle

CoffeeController --down-> AmericanoFactory
CoffeeController --down->  CaffeLatteFactory
CoffeeController --down-> CappouccionoFactory
CoffeeController --down-> CortadoFactory
CoffeeController --down-> ExpressoFactory
CoffeeController --down-> FlateWhiteFactory
CoffeeController --down-> LatteMacchiatoFactory
CoffeeController --down-> LungoFactory
CoffeeController --down-> MacchiatoFactory
CoffeeController --down-> MochaFactory

UserController --> App
UserController --up--> UserMapper



'CONFIG
'/////////////////////////////////////
package config{
class SessionConfig{
+ SessionHandler: sessionconfig()
}
class ThymeleafConfig{
 + TemplateEngine: templateEngine()
 }
 }
}

SessionConfig <-- app
ThymeleafConfig <-- app

'RESOURCES
package resources{

'PUBLIC
'/////////////////////////////////////
package public{

'HTML
'/////////////////////////////////////////
package templates{
entity Index{}
entity Login{}
entity CreateAccount{}
entity CoffeeType{}
entity CoffeeBrands{}
entity Options{}
entity ColorPanel{}
entity CreatingPanel{}
entity AboutUs{}
entity ContactUs{}
entity Favorites{}

package templatesCoffeeTypes{
entity Americano_html
entity CaffeLatte_html
entity Cappoucciono_html
entity Cortado_html
entity Expresso_html
entity FlateWhit_html
entity LatteMacchiato_html
entity Lungo_html
entity Macchiato_html
entity Mocha_html
}
CoffeeTypes --> Americano_html
CoffeeTypes --> CaffeLatte_html
CoffeeTypes -->  Cappoucciono_html
CoffeeTypes -->  Cortado_html
CoffeeTypes -->  Expresso_html
CoffeeTypes -->  FlateWhit_html
CoffeeTypes -->  LatteMacchiato_html
CoffeeTypes -->  Lungo_html
CoffeeTypes -->  Macchiato_html
CoffeeTypes -->  Mocha_html

UserController ---down---> Index
UserController ---down---> Login
UserController ---down--- Login
UserController ---down---> CreateAccount
UserController <---down--- CreateAccount
UserController ---down---> CoffeeType
UserController ---down---> CoffeeBrands
UserController ---down---> Options
UserController <---down--- Options
UserController ---down---> ColorPanel
UserController <---down--- ColorPanel
UserController ---down---> CreatingPanel
UserController <---down--- CreatingPanel
UserController ---down---> AboutUs
UserController ---down---> ContactUs
UserController ---down---> Favorites
UserController <--down--- Favorites
}

'CSS
'/////////////////////////////////////////

package css{
entity StyleSheet{
*h1
*h2
*body
*navbar
*menu
*footer
*form
*form-submit
*btn
}
}

'JAVA SCRIPT
'////////////////////////////////////////

package js{
entity ColorPanel{}
entity CreatorPanel{}
entity Favorites{}

}

'IMAGES
'/////////////////////////////////////////

package img{
entity image{}
}
}
}







@enduml