@startuml

'JAVA
'//////////////////////////////////////////////
package app{
class App{
}
}


package java{

package coffeeTypes{

package americano{
class Americano{
- Bean: type
- int: milkQuantity
- int: waterQuantity
- int: caffeineQuantity
+ Bean: type()
+ int: milkQuantity()
+ int: waterQuantity()
+ int: caffeineQuantity()
}
class AmericanoFactory{
+ Coffee: createCoffee(String type)
}

}

package caffeLatte{
class CaffeLatte{
- Bean: type
- int: milkQuantity
- int: waterQuantity
- int: caffeineQuantity
+ Bean: type()
+ int: milkQuantity()
+ int: waterQuantity()
+ int: caffeineQuantity()
}
class CaffeLatteFactory{
+ Coffee: createCoffee(String type)
}
}

package cappoucciono{
class Cappoucciono{
- Bean: type
- int: milkQuantity
- int: waterQuantity
- int: caffeineQuantity
+ Bean: type()
+ int: milkQuantity()
+ int: waterQuantity()
+ int: caffeineQuantity()
}
class CappouccionoFactory{
+ Coffee: createCoffee(String type)
}
}

package cortado{
class Cortado{
- Bean: type
- int: milkQuantity
- int: waterQuantity
- int: caffeineQuantity
+ Bean: type()
+ int: milkQuantity()
+ int: waterQuantity()
+ int: caffeineQuantity()
}

class CortadoFactory{
+ Coffee: createCoffee(String type)
}
}

package expresso{
class Expresso{
- Bean: type
- int: milkQuantity
- int: waterQuantity
- int: caffeineQuantity
+ Bean: type()
+ int: milkQuantity()
+ int: waterQuantity()
+ int: caffeineQuantity()
}

class ExpressoFactory{
+ Coffee: createCoffee(String type)
}
}

package flatWhite{
class FlateWhite{
- Bean: type
- int: milkQuantity
- int: waterQuantity
- int: caffeineQuantity
+ Bean: type()
+ int: milkQuantity()
+ int: waterQuantity()
+ int: caffeineQuantity()
}
class FlateWhiteFactory{
+ Coffee: createCoffee(String type)
}
}

package latteMacchiato{
class LatteMacchiato{
- Bean: type
- int: milkQuantity
- int: waterQuantity
- int: caffeineQuantity
+ Bean: type()
+ int: milkQuantity()
+ int: waterQuantity()
+ int: caffeineQuantity()
}
class LatteMacchiatoFactory{
+ Coffee: createCoffee(String type)
}
}

package lungo{
class Lungo{
- Bean: type
- int: milkQuantity
- int: waterQuantity
- int: caffeineQuantity
+ Bean: type()
+ int: milkQuantity()
+ int: waterQuantity()
+ int: caffeineQuantity()
}

class LungoFactory{
+ Coffee: createCoffee(String type)
}
}

package macchiato{
class Macchiato{
- Bean: type
- int: milkQuantity
- int: waterQuantity
- int: caffeineQuantity
+ Bean: type()
+ int: milkQuantity()
+ int: waterQuantity()
+ int: caffeineQuantity()
 }
class MacchiatoFactory{
+ Coffee: createCoffee(String type)
}
}

package mocha{
class Mocha{
- Bean: type
- int: milkQuantity
- int: waterQuantity
- int: caffeineQuantity
+ Bean: type()
+ int: milkQuantity()
+ int: waterQuantity()
+ int: caffeineQuantity()
}

class MochaFactory{
+ Coffee: createCoffee(String type)
}
}
}

CoffeeFactory <|.. AmericanoFactory
CoffeeFactory <|.. CaffeLatteFactory
CoffeeFactory <|.. CappouccionoFactory
CoffeeFactory <|.. CortadoFactory
CoffeeFactory <|.. ExpressoFactory
CoffeeFactory <|.. FlateWhiteFactory
CoffeeFactory <|.. LatteMacchiatoFactory
CoffeeFactory <|.. LungoFactory
CoffeeFactory <|.. MacchiatoFactory
CoffeeFactory <|.. MochaFactory


'//////////////////////////////////////////////

package ingredients{
abstract class Ingredients{
protected Coffee coffee;
+ Bean: type()
+ int: milkQuantity()
+ int: waterQuantity()
+ int: caffeineQuantity()
}

class Milk {
+int: amount()
}
class Water {
+int: amount()
}
class Beans {
+int: amount
+String: CoffeBrands
+Color: color
+int: Solubility
}
}
Ingredients <|-- Milk
Ingredients <|-- Water
Ingredients <|-- Beans

'//////////////////////////////////////////////

package entities{
class Users{
- String: firstname
- String: lastname
- String: email
- String: password
}

interface Bean{
String: brand
color: color
int: solubility
}

interface Coffee{
- Bean: type()
- int: milkQuantity()
- int: waterQuantity()
- int: caffeineQuantity()
}
}

 Coffee <|.. Ingredients
 Coffee <|... Americano
 Coffee <|... CaffeLatte
 Coffee <|... Cappoucciono
 Coffee <|.. Cortado
 Coffee <|... Expresso
 Coffee <|... FlateWhite
 Coffee <|... LatteMacchiato
 Coffee <|... Lungo
 Coffee <|... Macchiato
 Coffee <|... Mocha

 Coffee <... AmericanoFactory
 Coffee <... CaffeLatteFactory
 Coffee <... CappouccionoFactory
 Coffee <... CortadoFactory
 Coffee <... ExpressoFactory
 Coffee <... FlateWhiteFactory
 Coffee <... LatteMacchiatoFactory
 Coffee <... LungoFactory
 Coffee <... MacchiatoFactory
 Coffee <... MochaFactory





interface CoffeeFactory{
+ Coffee: createCoffee(String type)
}

class Math{
}
package pesistences{
class UserMapper{
+ boolean: login()
+ boolean: creatUser()
+ list: displayFavorits
}

class ConnectionPool{
- ConnectionPool: instance
- HikariDatasource: ds
- Logger: LOGGER
- ConnectionPool: getInstance()
+ Connection: getConnection
+ void: close()
- HikariDataSource: createHikariConnectionPool()
}

}



'CONTROLLERS
'/////////////////////////////////////
package controllers{
class UserController{
+ void: addRoutes()
+ boolean: creatUser
}
}

'CONFIG
'/////////////////////////////////////
package config{
class SessionConfig{
+ SessionHandler: sessionconfig()
}
class ThymeleafConfig{
 + TemplateEngine: templateEngine()
 }
 }
}

'EXCEPTIONS
'/////////////////////////////////////
package exceptions{
class DatabaseExceptions
class exceptions
}




'RESOURCES
package resources{

'PUBLIC
'/////////////////////////////////////
package public{

'HTML
'/////////////////////////////////////////
package templates{
entity Index{}
entity Login{}
entity CreateAccount{}
entity CoffeeType{}
entity CoffeeBrands{}
entity Options{}
entity ColorPanel{}
entity CreatingPanel{}
entity AboutUs{}
entity ContactUs{}
entity Favorites{}
}

'CSS
'/////////////////////////////////////////

package css{
entity StyleSheet{}
}

'JAVA SCRIPT
'////////////////////////////////////////

package js{
entity ColorPanel{}
entity CreatorPanel{}
}

'IMAGES
'/////////////////////////////////////////

package img{
entity image{}
}
}
}







@enduml